### ISSUE TITLE
Client for iOS

### ISSUE THREAD

**Issue by kotleni** [uadata/uadata#1]
https://github.com/kotleni/uadata-ios

**Comment by uadata** [comment]
Wow, great idea. Do you need any API improvements for the app? We're adding new data objects at the moment, like: https://uadata.net/how-many-children-died-from-russia-aggression-2022

**Comment by kotleni** [comment]
This doesn't make much sense since I don't have an Apple developer license (to post this) 😃🇺🇦

**Comment by kotleni** [comment]
Hello! I can now make and publish a client for UADATA in the AppStore (iOS). Do you mind if I add a small ad banner in the app? :D

**Comment by kotleni** [comment]
And I can use the name aka "UADATA Tracker"

**Comment by kotleni** [comment]
There is good news! I now have an Apple license! 🤪
